{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'database_connect'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\upload_data_to_db\\upload.ipynb Cell 1\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[1;34m()\u001b[0m\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/Users/avane/Downloads/MLproject-main/MLproject-main/sensor-fault-detection/upload_data_to_db/upload.ipynb#W0sZmlsZQ%3D%3D?line=0'>1</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mdatabase_connect\u001b[39;00m \u001b[39mimport\u001b[39;00m mongo_operation \u001b[39mas\u001b[39;00m mongo\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/avane/Downloads/MLproject-main/MLproject-main/sensor-fault-detection/upload_data_to_db/upload.ipynb#W0sZmlsZQ%3D%3D?line=2'>3</a>\u001b[0m client_url\u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39mmongodb+srv://hrisikesh:hrisikeshAndineuron@cluster0.iq9nlei.mongodb.net/?retryWrites=true&w=majority\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/avane/Downloads/MLproject-main/MLproject-main/sensor-fault-detection/upload_data_to_db/upload.ipynb#W0sZmlsZQ%3D%3D?line=3'>4</a>\u001b[0m database_name \u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39msensor\u001b[39m\u001b[39m\"\u001b[39m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'database_connect'"
     ]
    }
   ],
   "source": [
    "from database_connect import mongo_operation as mongo\n",
    "\n",
    "client_url= \"mongodb+srv://hrisikesh:hrisikeshAndineuron@cluster0.iq9nlei.mongodb.net/?retryWrites=true&w=majority\"\n",
    "database_name = \"sensor\"\n",
    "\n",
    "\n",
    "def upload_files_to_mongodb(\n",
    "    mongo_client_con_string,\n",
    "    database_name,\n",
    "    datasets_dir_name):\n",
    "  \n",
    "  for file in os.listdir(datasets_dir_name):\n",
    "    if file.endswith('.csv'):\n",
    "      file_name = file.split('.')[0]\n",
    "\n",
    "      mongo_connection = mongo(\n",
    "          client_url = mongo_client_con_string,\n",
    "          database_name= database_name,\n",
    "          collection_name= file_name\n",
    "      )\n",
    "\n",
    "      file_path = os.path.join(datasets_dir_name, file_name)\n",
    "      mongo_connection.bulk_insert(file)\n",
    "      print(f\"{file_name} is uploaded to mongodb\")\n",
    "\n",
    "\n",
    "upload_files_to_mongodb(\n",
    "    mongo_client_con_string= client_url,\n",
    "    database_name = database_name,\n",
    "    datasets_dir_name= \"/content\"\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import json\n",
    "from pymongo import MongoClient\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pymongo==3.6 in c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages (3.6.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -ymongo (c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ymongo (c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ymongo (c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ymongo (c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ymongo (c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ymongo (c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages)\n"
     ]
    }
   ],
   "source": [
    "pip install pymongo==3.6"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "pip install pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Uniform Resource Identifier (URI) for connecting to the MongoDB cluster\n",
    "uri = \"mongodb+srv://avaneeshpathak900:03717anujP@cluster0.tszy1a8.mongodb.net/Avaneesh?retryWrites=true&w=majority\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# Create a new client and connect to the server\n",
    "client = MongoClient(uri)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: dnspython in c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages (2.2.1)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -ymongo (c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ymongo (c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ymongo (c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ymongo (c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ymongo (c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ymongo (c:\\users\\avane\\downloads\\mlproject-main\\mlproject-main\\sensor-fault-detection\\venv\\lib\\site-packages)\n"
     ]
    }
   ],
   "source": [
    "!pip install dnspython\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "import dns\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create database name and collection name\n",
    "DATABASE_NAME = 'Avaneesh'\n",
    "COLLECTION_NAME = 'waferfault'\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Read the CSV file into a pandas DataFrame\n",
    "df = pd.read_csv(r\"D:\\sensor-fault-detection\\notebooks\\wafer_23012020_041211.csv\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Convert the data into JSON format\n",
    "json_records = df.to_dict(orient='records')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "ename": "OperationFailure",
     "evalue": "Unsupported OP_QUERY command: insert. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mOperationFailure\u001b[0m                          Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\upload_data_to_db\\upload.ipynb Cell 12\u001b[0m in \u001b[0;36m<cell line: 3>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/avane/Downloads/MLproject-main/MLproject-main/sensor-fault-detection/upload_data_to_db/upload.ipynb#X14sZmlsZQ%3D%3D?line=0'>1</a>\u001b[0m \u001b[39m# Insert the JSON records into the specified collection within the database\u001b[39;00m\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/Users/avane/Downloads/MLproject-main/MLproject-main/sensor-fault-detection/upload_data_to_db/upload.ipynb#X14sZmlsZQ%3D%3D?line=2'>3</a>\u001b[0m client[DATABASE_NAME][COLLECTION_NAME]\u001b[39m.\u001b[39;49minsert_many(json_records)\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\collection.py:741\u001b[0m, in \u001b[0;36mCollection.insert_many\u001b[1;34m(self, documents, ordered, bypass_document_validation, session)\u001b[0m\n\u001b[0;32m    739\u001b[0m blk \u001b[39m=\u001b[39m _Bulk(\u001b[39mself\u001b[39m, ordered, bypass_document_validation)\n\u001b[0;32m    740\u001b[0m blk\u001b[39m.\u001b[39mops \u001b[39m=\u001b[39m [doc \u001b[39mfor\u001b[39;00m doc \u001b[39min\u001b[39;00m gen()]\n\u001b[1;32m--> 741\u001b[0m blk\u001b[39m.\u001b[39;49mexecute(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mwrite_concern\u001b[39m.\u001b[39;49mdocument, session\u001b[39m=\u001b[39;49msession)\n\u001b[0;32m    742\u001b[0m \u001b[39mreturn\u001b[39;00m InsertManyResult(inserted_ids, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mwrite_concern\u001b[39m.\u001b[39macknowledged)\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\bulk.py:432\u001b[0m, in \u001b[0;36m_Bulk.execute\u001b[1;34m(self, write_concern, session)\u001b[0m\n\u001b[0;32m    430\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mexecute_no_results(sock_info, generator)\n\u001b[0;32m    431\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m--> 432\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mexecute_command(generator, write_concern, session)\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\bulk.py:322\u001b[0m, in \u001b[0;36m_Bulk.execute_command\u001b[1;34m(self, generator, write_concern, session)\u001b[0m\n\u001b[0;32m    320\u001b[0m client \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mcollection\u001b[39m.\u001b[39mdatabase\u001b[39m.\u001b[39mclient\n\u001b[0;32m    321\u001b[0m \u001b[39mwith\u001b[39;00m client\u001b[39m.\u001b[39m_tmp_session(session) \u001b[39mas\u001b[39;00m s:\n\u001b[1;32m--> 322\u001b[0m     client\u001b[39m.\u001b[39;49m_retry_with_session(\n\u001b[0;32m    323\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mis_retryable, retryable_bulk, s, \u001b[39mself\u001b[39;49m)\n\u001b[0;32m    325\u001b[0m \u001b[39mif\u001b[39;00m full_result[\u001b[39m\"\u001b[39m\u001b[39mwriteErrors\u001b[39m\u001b[39m\"\u001b[39m] \u001b[39mor\u001b[39;00m full_result[\u001b[39m\"\u001b[39m\u001b[39mwriteConcernErrors\u001b[39m\u001b[39m\"\u001b[39m]:\n\u001b[0;32m    326\u001b[0m     \u001b[39mif\u001b[39;00m full_result[\u001b[39m'\u001b[39m\u001b[39mwriteErrors\u001b[39m\u001b[39m'\u001b[39m]:\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\mongo_client.py:1076\u001b[0m, in \u001b[0;36mMongoClient._retry_with_session\u001b[1;34m(self, retryable, func, session, bulk)\u001b[0m\n\u001b[0;32m   1073\u001b[0m         \u001b[39mif\u001b[39;00m is_retrying():\n\u001b[0;32m   1074\u001b[0m             \u001b[39m# Reset the transaction id and retry the operation.\u001b[39;00m\n\u001b[0;32m   1075\u001b[0m             session\u001b[39m.\u001b[39m_retry_transaction_id()\n\u001b[1;32m-> 1076\u001b[0m         \u001b[39mreturn\u001b[39;00m func(session, sock_info, retryable)\n\u001b[0;32m   1077\u001b[0m \u001b[39mexcept\u001b[39;00m ServerSelectionTimeoutError:\n\u001b[0;32m   1078\u001b[0m     \u001b[39mif\u001b[39;00m is_retrying():\n\u001b[0;32m   1079\u001b[0m         \u001b[39m# The application may think the write was never attempted\u001b[39;00m\n\u001b[0;32m   1080\u001b[0m         \u001b[39m# if we raise ServerSelectionTimeoutError on the retry\u001b[39;00m\n\u001b[0;32m   1081\u001b[0m         \u001b[39m# attempt. Raise the original exception instead.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\bulk.py:316\u001b[0m, in \u001b[0;36m_Bulk.execute_command.<locals>.retryable_bulk\u001b[1;34m(session, sock_info, retryable)\u001b[0m\n\u001b[0;32m    315\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mretryable_bulk\u001b[39m(session, sock_info, retryable):\n\u001b[1;32m--> 316\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_command(\n\u001b[0;32m    317\u001b[0m         generator, write_concern, session, sock_info, op_id,\n\u001b[0;32m    318\u001b[0m         retryable, full_result)\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\bulk.py:281\u001b[0m, in \u001b[0;36m_Bulk._execute_command\u001b[1;34m(self, generator, write_concern, session, sock_info, op_id, retryable, full_result)\u001b[0m\n\u001b[0;32m    279\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m to_send:\n\u001b[0;32m    280\u001b[0m     \u001b[39mraise\u001b[39;00m InvalidOperation(\u001b[39m\"\u001b[39m\u001b[39mcannot do an empty bulk write\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m--> 281\u001b[0m result \u001b[39m=\u001b[39m bwc\u001b[39m.\u001b[39;49mwrite_command(request_id, msg, to_send)\n\u001b[0;32m    282\u001b[0m client\u001b[39m.\u001b[39m_receive_cluster_time(result, session)\n\u001b[0;32m    283\u001b[0m results\u001b[39m.\u001b[39mappend((run\u001b[39m.\u001b[39midx_offset, result))\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\message.py:664\u001b[0m, in \u001b[0;36m_BulkWriteContext.write_command\u001b[1;34m(self, request_id, msg, docs)\u001b[0m\n\u001b[0;32m    662\u001b[0m     start \u001b[39m=\u001b[39m datetime\u001b[39m.\u001b[39mdatetime\u001b[39m.\u001b[39mnow()\n\u001b[0;32m    663\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 664\u001b[0m     reply \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msock_info\u001b[39m.\u001b[39;49mwrite_command(request_id, msg)\n\u001b[0;32m    665\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mpublish:\n\u001b[0;32m    666\u001b[0m         duration \u001b[39m=\u001b[39m (datetime\u001b[39m.\u001b[39mdatetime\u001b[39m.\u001b[39mnow() \u001b[39m-\u001b[39m start) \u001b[39m+\u001b[39m duration\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\pool.py:566\u001b[0m, in \u001b[0;36mSocketInfo.write_command\u001b[1;34m(self, request_id, msg)\u001b[0m\n\u001b[0;32m    563\u001b[0m result \u001b[39m=\u001b[39m reply\u001b[39m.\u001b[39mcommand_response()\n\u001b[0;32m    565\u001b[0m \u001b[39m# Raises NotMasterError or OperationFailure.\u001b[39;00m\n\u001b[1;32m--> 566\u001b[0m helpers\u001b[39m.\u001b[39;49m_check_command_response(result)\n\u001b[0;32m    567\u001b[0m \u001b[39mreturn\u001b[39;00m result\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\helpers.py:146\u001b[0m, in \u001b[0;36m_check_command_response\u001b[1;34m(response, msg, allowable_errors, parse_write_concern_error)\u001b[0m\n\u001b[0;32m    143\u001b[0m     \u001b[39mraise\u001b[39;00m CursorNotFound(errmsg, code, response)\n\u001b[0;32m    145\u001b[0m msg \u001b[39m=\u001b[39m msg \u001b[39mor\u001b[39;00m \u001b[39m\"\u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m--> 146\u001b[0m \u001b[39mraise\u001b[39;00m OperationFailure(msg \u001b[39m%\u001b[39m errmsg, code, response)\n",
      "\u001b[1;31mOperationFailure\u001b[0m: Unsupported OP_QUERY command: insert. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal"
     ]
    }
   ],
   "source": [
    "# Insert the JSON records into the specified collection within the database\n",
    "\n",
    "client[DATABASE_NAME][COLLECTION_NAME].insert_many(json_records)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pinged your deployment. You successfully connected to MongoDB!\n"
     ]
    }
   ],
   "source": [
    "# Send a ping to confirm a successful connection\n",
    "try:\n",
    "    client.admin.command('ping')\n",
    "    print(\"Pinged your deployment. You successfully connected to MongoDB!\")\n",
    "except Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "# Close the MongoDB connection\n",
    "client.close()\n",
    "\n",
    "client.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "from pymongo.mongo_client import MongoClient\n",
    "from pymongo.server_api import ServerApi\n",
    "\n",
    "uri = \"mongodb+srv://avaneeshpathak900:<password>@cluster0.tszy1a8.mongodb.net/?retryWrites=true&w=majority\"\n",
    "\n",
    "# Create a new client and connect to the server\n",
    "client = MongoClient(uri, server_api=ServerApi('1'))\n",
    "\n",
    "# Send a ping to confirm a successful connection\n",
    "try:\n",
    "    client.admin.command('ping')\n",
    "    print(\"Pinged your deployment. You successfully connected to MongoDB!\")\n",
    "except Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "ename": "OperationFailure",
     "evalue": "Unsupported OP_QUERY command: insert. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mOperationFailure\u001b[0m                          Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\upload_data_to_db\\upload.ipynb Cell 16\u001b[0m in \u001b[0;36m<cell line: 24>\u001b[1;34m()\u001b[0m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/avane/Downloads/MLproject-main/MLproject-main/sensor-fault-detection/upload_data_to_db/upload.ipynb#X21sZmlsZQ%3D%3D?line=19'>20</a>\u001b[0m json_records \u001b[39m=\u001b[39m df\u001b[39m.\u001b[39mto_dict(orient\u001b[39m=\u001b[39m\u001b[39m'\u001b[39m\u001b[39mrecords\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/avane/Downloads/MLproject-main/MLproject-main/sensor-fault-detection/upload_data_to_db/upload.ipynb#X21sZmlsZQ%3D%3D?line=21'>22</a>\u001b[0m \u001b[39m# Insert the JSON records into the specified collection within the database\u001b[39;00m\n\u001b[1;32m---> <a href='vscode-notebook-cell:/c%3A/Users/avane/Downloads/MLproject-main/MLproject-main/sensor-fault-detection/upload_data_to_db/upload.ipynb#X21sZmlsZQ%3D%3D?line=23'>24</a>\u001b[0m client[DATABASE_NAME][COLLECTION_NAME]\u001b[39m.\u001b[39;49minsert_many(json_records)\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/avane/Downloads/MLproject-main/MLproject-main/sensor-fault-detection/upload_data_to_db/upload.ipynb#X21sZmlsZQ%3D%3D?line=25'>26</a>\u001b[0m \u001b[39m# # Close the MongoDB connection\u001b[39;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/avane/Downloads/MLproject-main/MLproject-main/sensor-fault-detection/upload_data_to_db/upload.ipynb#X21sZmlsZQ%3D%3D?line=26'>27</a>\u001b[0m \u001b[39m# client.close()\u001b[39;00m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/avane/Downloads/MLproject-main/MLproject-main/sensor-fault-detection/upload_data_to_db/upload.ipynb#X21sZmlsZQ%3D%3D?line=27'>28</a>\u001b[0m \n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/avane/Downloads/MLproject-main/MLproject-main/sensor-fault-detection/upload_data_to_db/upload.ipynb#X21sZmlsZQ%3D%3D?line=28'>29</a>\u001b[0m \u001b[39m# client.close()\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\collection.py:741\u001b[0m, in \u001b[0;36mCollection.insert_many\u001b[1;34m(self, documents, ordered, bypass_document_validation, session)\u001b[0m\n\u001b[0;32m    739\u001b[0m blk \u001b[39m=\u001b[39m _Bulk(\u001b[39mself\u001b[39m, ordered, bypass_document_validation)\n\u001b[0;32m    740\u001b[0m blk\u001b[39m.\u001b[39mops \u001b[39m=\u001b[39m [doc \u001b[39mfor\u001b[39;00m doc \u001b[39min\u001b[39;00m gen()]\n\u001b[1;32m--> 741\u001b[0m blk\u001b[39m.\u001b[39;49mexecute(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mwrite_concern\u001b[39m.\u001b[39;49mdocument, session\u001b[39m=\u001b[39;49msession)\n\u001b[0;32m    742\u001b[0m \u001b[39mreturn\u001b[39;00m InsertManyResult(inserted_ids, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mwrite_concern\u001b[39m.\u001b[39macknowledged)\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\bulk.py:432\u001b[0m, in \u001b[0;36m_Bulk.execute\u001b[1;34m(self, write_concern, session)\u001b[0m\n\u001b[0;32m    430\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mexecute_no_results(sock_info, generator)\n\u001b[0;32m    431\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m--> 432\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mexecute_command(generator, write_concern, session)\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\bulk.py:322\u001b[0m, in \u001b[0;36m_Bulk.execute_command\u001b[1;34m(self, generator, write_concern, session)\u001b[0m\n\u001b[0;32m    320\u001b[0m client \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mcollection\u001b[39m.\u001b[39mdatabase\u001b[39m.\u001b[39mclient\n\u001b[0;32m    321\u001b[0m \u001b[39mwith\u001b[39;00m client\u001b[39m.\u001b[39m_tmp_session(session) \u001b[39mas\u001b[39;00m s:\n\u001b[1;32m--> 322\u001b[0m     client\u001b[39m.\u001b[39;49m_retry_with_session(\n\u001b[0;32m    323\u001b[0m         \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mis_retryable, retryable_bulk, s, \u001b[39mself\u001b[39;49m)\n\u001b[0;32m    325\u001b[0m \u001b[39mif\u001b[39;00m full_result[\u001b[39m\"\u001b[39m\u001b[39mwriteErrors\u001b[39m\u001b[39m\"\u001b[39m] \u001b[39mor\u001b[39;00m full_result[\u001b[39m\"\u001b[39m\u001b[39mwriteConcernErrors\u001b[39m\u001b[39m\"\u001b[39m]:\n\u001b[0;32m    326\u001b[0m     \u001b[39mif\u001b[39;00m full_result[\u001b[39m'\u001b[39m\u001b[39mwriteErrors\u001b[39m\u001b[39m'\u001b[39m]:\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\mongo_client.py:1076\u001b[0m, in \u001b[0;36mMongoClient._retry_with_session\u001b[1;34m(self, retryable, func, session, bulk)\u001b[0m\n\u001b[0;32m   1073\u001b[0m         \u001b[39mif\u001b[39;00m is_retrying():\n\u001b[0;32m   1074\u001b[0m             \u001b[39m# Reset the transaction id and retry the operation.\u001b[39;00m\n\u001b[0;32m   1075\u001b[0m             session\u001b[39m.\u001b[39m_retry_transaction_id()\n\u001b[1;32m-> 1076\u001b[0m         \u001b[39mreturn\u001b[39;00m func(session, sock_info, retryable)\n\u001b[0;32m   1077\u001b[0m \u001b[39mexcept\u001b[39;00m ServerSelectionTimeoutError:\n\u001b[0;32m   1078\u001b[0m     \u001b[39mif\u001b[39;00m is_retrying():\n\u001b[0;32m   1079\u001b[0m         \u001b[39m# The application may think the write was never attempted\u001b[39;00m\n\u001b[0;32m   1080\u001b[0m         \u001b[39m# if we raise ServerSelectionTimeoutError on the retry\u001b[39;00m\n\u001b[0;32m   1081\u001b[0m         \u001b[39m# attempt. Raise the original exception instead.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\bulk.py:316\u001b[0m, in \u001b[0;36m_Bulk.execute_command.<locals>.retryable_bulk\u001b[1;34m(session, sock_info, retryable)\u001b[0m\n\u001b[0;32m    315\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mretryable_bulk\u001b[39m(session, sock_info, retryable):\n\u001b[1;32m--> 316\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_execute_command(\n\u001b[0;32m    317\u001b[0m         generator, write_concern, session, sock_info, op_id,\n\u001b[0;32m    318\u001b[0m         retryable, full_result)\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\bulk.py:281\u001b[0m, in \u001b[0;36m_Bulk._execute_command\u001b[1;34m(self, generator, write_concern, session, sock_info, op_id, retryable, full_result)\u001b[0m\n\u001b[0;32m    279\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m to_send:\n\u001b[0;32m    280\u001b[0m     \u001b[39mraise\u001b[39;00m InvalidOperation(\u001b[39m\"\u001b[39m\u001b[39mcannot do an empty bulk write\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m--> 281\u001b[0m result \u001b[39m=\u001b[39m bwc\u001b[39m.\u001b[39;49mwrite_command(request_id, msg, to_send)\n\u001b[0;32m    282\u001b[0m client\u001b[39m.\u001b[39m_receive_cluster_time(result, session)\n\u001b[0;32m    283\u001b[0m results\u001b[39m.\u001b[39mappend((run\u001b[39m.\u001b[39midx_offset, result))\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\message.py:664\u001b[0m, in \u001b[0;36m_BulkWriteContext.write_command\u001b[1;34m(self, request_id, msg, docs)\u001b[0m\n\u001b[0;32m    662\u001b[0m     start \u001b[39m=\u001b[39m datetime\u001b[39m.\u001b[39mdatetime\u001b[39m.\u001b[39mnow()\n\u001b[0;32m    663\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 664\u001b[0m     reply \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msock_info\u001b[39m.\u001b[39;49mwrite_command(request_id, msg)\n\u001b[0;32m    665\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mpublish:\n\u001b[0;32m    666\u001b[0m         duration \u001b[39m=\u001b[39m (datetime\u001b[39m.\u001b[39mdatetime\u001b[39m.\u001b[39mnow() \u001b[39m-\u001b[39m start) \u001b[39m+\u001b[39m duration\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\pool.py:566\u001b[0m, in \u001b[0;36mSocketInfo.write_command\u001b[1;34m(self, request_id, msg)\u001b[0m\n\u001b[0;32m    563\u001b[0m result \u001b[39m=\u001b[39m reply\u001b[39m.\u001b[39mcommand_response()\n\u001b[0;32m    565\u001b[0m \u001b[39m# Raises NotMasterError or OperationFailure.\u001b[39;00m\n\u001b[1;32m--> 566\u001b[0m helpers\u001b[39m.\u001b[39;49m_check_command_response(result)\n\u001b[0;32m    567\u001b[0m \u001b[39mreturn\u001b[39;00m result\n",
      "File \u001b[1;32mc:\\Users\\avane\\Downloads\\MLproject-main\\MLproject-main\\sensor-fault-detection\\venv\\lib\\site-packages\\pymongo\\helpers.py:146\u001b[0m, in \u001b[0;36m_check_command_response\u001b[1;34m(response, msg, allowable_errors, parse_write_concern_error)\u001b[0m\n\u001b[0;32m    143\u001b[0m     \u001b[39mraise\u001b[39;00m CursorNotFound(errmsg, code, response)\n\u001b[0;32m    145\u001b[0m msg \u001b[39m=\u001b[39m msg \u001b[39mor\u001b[39;00m \u001b[39m\"\u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m\n\u001b[1;32m--> 146\u001b[0m \u001b[39mraise\u001b[39;00m OperationFailure(msg \u001b[39m%\u001b[39m errmsg, code, response)\n",
      "\u001b[1;31mOperationFailure\u001b[0m: Unsupported OP_QUERY command: insert. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal"
     ]
    }
   ],
   "source": [
    "\n",
    "import pandas as pd\n",
    "import json\n",
    "from pymongo import MongoClient\n",
    "\n",
    "# Uniform Resource Identifier (URI) for connecting to the MongoDB cluster\n",
    "uri = \"mongodb+srv://avaneeshpathak900:03717anujP@cluster0.tszy1a8.mongodb.net/Avaneesh?retryWrites=true&w=majority\"\n",
    "\n",
    "# Create a new client and connect to the MongoDB server\n",
    "client = MongoClient(uri)\n",
    "\n",
    "# Create database name and collection name\n",
    "DATABASE_NAME = 'Avaneesh'\n",
    "COLLECTION_NAME = 'waferfault'\n",
    "\n",
    "# Read the CSV file into a pandas DataFrame\n",
    "df = pd.read_csv(r\"D:\\sensor-fault-detection\\notebooks\\wafer_23012020_041211.csv\")\n",
    "\n",
    "\n",
    "# Convert the data into JSON format\n",
    "json_records = df.to_dict(orient='records')\n",
    "\n",
    "# Insert the JSON records into the specified collection within the database\n",
    "\n",
    "client[DATABASE_NAME][COLLECTION_NAME].insert_many(json_records)\n",
    "\n",
    "# # Close the MongoDB connection\n",
    "# client.close()\n",
    "\n",
    "# client.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.0"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
